### ISSUE TITLE
Latest charon_image_tag is not updated into canary clusters after each charon-package-published event dispatch

### ISSUE THREAD

**Issue by sugh01** [ObolNetwork/charon-k8s-distributed-validator-cluster#100]
# 🐞 Bug Report

After every `charon` deployment, it triggers a repository dispatch on  `charon-k8s-distributed-validator-cluster` and sends the latest commit hash. But the` deploy_cluster.yaml` does not update the image hash before deploying the cluster to k8s.

<img width="1236" alt="image" src="https://github.com/ObolNetwork/charon-k8s-distributed-validator-cluster/assets/19183308/c4dba129-9ee8-40ac-9c61-7e1e68d8162c">

**Comment by aly-obol** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/kWTqq1fvxK/estimate/11) in Sizing - Platform

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
