### ISSUE TITLE
Automate DKG/Relay Load tests

### ISSUE THREAD

**Issue by sugh01** [ObolNetwork/charon-k8s-distributed-validator-cluster#118]
# 🎯 Problem to be solved

Automated DKG load tests built here - [PR](https://app.zenhub.com/workspaces/obol-workspace-648c1170ee94656741353327/issues/gh/obolnetwork/charon-k8s-distributed-validator-cluster/118)

Suggetsion to add a repository trigger with a relay url arg? Then could potentially automate tests after a dev relay deploy.

# 🛠️ Proposed solution
Use Github workflow to run the tests. 
Send CHARON_P2P_RELAYS as the run parmeter.

# 🧪 Tests
Workflow should be able to trigger load tests by taking the `Relay` as user defined inputs

# ❌ Out of Scope
Generating definition files with SDK

**Comment by aly-obol** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon-k8s-distributed-validator-cluster/118?planning-poker) with Zenhub @aly-obol @haroldsphinx @LukeHackett12 @sugh01
