### ISSUE TITLE
Simplify charon-k8s deployment scripts

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon-k8s-distributed-validator-cluster#148]
## 🎯 Problem to be solved
The current charon-k8s deployment process involves multiple scripts, making it complex and potentially error-prone for users. We need to simplify this process to improve usability and reduce potential mistakes.

## 🛠️ Proposed solution
- [ ] Create a new Golang/Python script that combines functionality of existing deployment scripts
- [ ] Implement a standard CLI for the new script
- [ ] Ensure the new script covers all deployment scenarios currently supported
- [ ] Add clear, descriptive help messages for each CLI option

**Comment by sugh01** [comment]
I would suggest Golang :)
