### ISSUE TITLE
Create k8s templates for VCs voluntary exit

### ISSUE THREAD

**Issue by aly-obol** [ObolNetwork/charon-k8s-distributed-validator-cluster#75]
## Problem to be solved
We need our charon-k8s templates to support the VCs voluntary exit for Lighthouse and Lodestar.

## Proposed solution
- Create k8s templates for lighthouse and lodestar voluntary exit
- Update the readme doc

**Comment by thomasheremans** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/kTqTIeSZ2w/estimate/23) in Ongoing Sizing

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
